wget wwtweb.blob.core.windows.net/docs/images/MapOfEarth.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast4.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast4Flat.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast16.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast16Flat.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast64.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast64Flat.jpg
wget wwtweb.blob.core.windows.net/docs/images/ToastMapOfEarth.jpg
wget wwtweb.blob.core.windows.net/docs/images/ToastLinks.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast4FlatInside.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast4FlatOutside.jpg
wget wwtweb.blob.core.windows.net/docs/images/ToastPaths.jpg
wget wwtweb.blob.core.windows.net/docs/images/toastedredplanet.jpg
wget wwtweb.blob.core.windows.net/docs/images/Toast_Input.bmp
wget wwtweb.blob.core.windows.net/docs/images/Toast_Output.bmp
